spring:
  application:
    name: gateway-service

server:
  port: 8300


zuul:
  #Service will be mapped under the /api URI
  prefix: /armadilloapi.com/v1_0/api
  routes:
    eureka-service:
      path: /eureka-service/**
      url: http://localhost:8301
    billing-service:
      path: /billing-service/**
      url: http://localhost:8302
    client-service:
      path: /client-service/**
      url: http://localhost:8303
    datain-service:
      path: /datain-service/**
      url: http://localhost:8304      